[versions]
agp = "8.13.0"
kotlin = "2.1.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"

coreSplashscreen = "1.0.0"
navVersion = "2.9.5"
serialization = "1.9.0"
materialIcon = "1.7.8"
ksp = "2.2.20-2.0.4"
roomKtx = "2.8.2"
roomRuntime = "2.8.2"
lottie = "6.6.10"
lottieCompose = "6.6.10"
dataStore = "1.1.4"
atomicfu = "0.29.0"
accompanistSystemuicontroller = "0.36.0"
retrofit = "3.0.0"
gson = "2.13.2"
hilt_version="2.57.2"
hilt_navigation="1.1.0"
coilCompose = "2.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Splash Screen
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
#Navigation
navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref = "navVersion"}
navigation-serialization-json = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref = "serialization"}
#Room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
#DataStore
dataStorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" } #Provides Thread Safe Singleton
#Material Icon
material-icon = { module = "androidx.compose.material:material-icons-extended", version.ref ="materialIcon"}
#Lottie
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = {module = "com.airbnb.android:lottie-compose" ,version.ref = "lottieCompose"}
#SystemUIController
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
#Retrofit
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-converter = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
#Gson
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}
#Hilt
hilt-core = {module = "com.google.dagger:hilt-android", version.ref = "hilt_version"}
hilt-navigation = {module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_navigation"}
hilt_compiler = {module = "com.google.dagger:hilt-compiler", version.ref = "hilt_version"}
#Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}

[bundles]

navigation = [
    "navigation-compose",
    "navigation-serialization-json"
]

room = ["room-ktx","room-runtime"]

dataStore = [
    "dataStorePreferences",
    "atomicfu"
]

retrofit = [
    "retrofit-core",
    "retrofit-converter",
]

hilt = [
    "hilt-core",
    "hilt-navigation",
]